### ISSUE TITLE
Traspasar bocetos tarjetas de click a prototipo en Figma

### ISSUE THREAD

**Issue by Tolevats** [Tolevats/DEV015-dataverse-chat#11]
Considerar 3 pantallas en baja fidelidad primero, luego en alta

**Comment by Tolevats** [comment]
¡No olvidarme de propuesta diseño para chat grupal!

**Comment by Carolinartz** [comment]
nunca completaste los prototiopos, según el acuerdo que habiamos quedado antes de que salgas a feriado!
